### ISSUE TITLE
Failed to upload image

### ISSUE THREAD

**Issue by xBenjo** [SunsetTechuila/imaged-folders#1]
I tried to add the attached image to a folder and it wouldn't work. I made sure it was square and tried compressing it lower than other images with no success. What are the image requirements? Thanks 
![MonkeyBuisness](https://github.com/SunsetTechuila/imaged-folders/assets/138199616/753ef06e-1e24-4135-930c-d083544cdb05)

**Comment by SunsetTechuila** [comment]
> I made sure it was square

Not necessary, it will be cropped automatically

> tried compressing it

There is built-in compressing

**Comment by SunsetTechuila** [comment]
>Run `spicetify enable-devtools`, press ctrl+shift+i, go to console, then try to add image and you will see the exact error

or install the [latest version](https://github.com/SunsetTechuila/imaged-folders/blob/main/dist/imaged-folders.js) [manually](https://spicetify.app/docs/advanced-usage/extensions) (you will need to remove the marketplace version)

**Comment by xBenjo** [comment]
I got this error message
![image](https://github.com/SunsetTechuila/imaged-folders/assets/138199616/9b7ca336-60c6-4ad4-934f-ab42a03f5aae)

**Comment by SunsetTechuila** [comment]
local storage space is very limited - only [up to 10mb](https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria#web_storage)
and the only thing you can do - clean it and don't use extensions/themes/apps that don't use it rationally

run this code in devtools console to get key names of the items with max size:
```js
var _lsTotal = 0,_xLen, _x; var entries = []; for (_x in localStorage) {     if (!localStorage.hasOwnProperty(_x)) {         continue;     }     _xLen = ((localStorage[_x].length + _x.length) * 2);     _lsTotal += _xLen;     entries.push({label: _x.substr(0, 50), size: (_xLen / 1024) /* in KB */}); }; entries.sort((a, b) => {    if(a.size === b.size) return 0;return a.size > b.size ? -1 : 1;}); entries.forEach(entry => {     console.log(entry.label +" = " + entry.size.toFixed(2)+" KB"); }); console.log("Total = " + (_lsTotal / 1024).toFixed(2) + " KB");
```
[source](https://stackoverflow.com/questions/4391575/how-to-find-the-size-of-localstorage#comment120846363_15720835)

to remove an item use [`localStorage.removeItem("keyName")`](https://developer.mozilla.org/en-US/docs/Web/API/Storage/removeItem)

**Comment by xBenjo** [comment]
it seems my theme is taking up about 9mb. A big chunk of that is a 2.5 mb readme called "hazy:playlistBg:readme" how would I use the localStorage.removeItem() command to remove it? I understand if you would rather me send this to the theme dev instead

**Comment by SunsetTechuila** [comment]
```js
localStorage.removeItem("hazy:playlistBg:readme")
```

**Comment by xBenjo** [comment]
Thank you
