### ISSUE TITLE
About uploading photo for the folder extension

### ISSUE THREAD

**Issue by KeshavKalaivaniSuresh** [SunsetTechuila/imaged-folders#2]
I have downloaded the extension for imaged folder but it doesnt even show me the option me any option to upload photo when i right click on the folder. I saw that u already saw that u closed similar problem but for me i got no error nothing, didnt get the option in the first place

**Comment by SunsetTechuila** [comment]
spicetify/spotify versions?

**Comment by KeshavKalaivaniSuresh** [comment]
yea
I am using the spicetify spotify version 
![Screenshot (150)](https://github.com/SunsetTechuila/imaged-folders/assets/152434390/15940138-00f3-4b79-b853-b2d01a323302)

**Comment by SunsetTechuila** [comment]
What versions of Spotify and Spicetify are you using?

**Comment by KeshavKalaivaniSuresh** [comment]
![Screenshot (151)](https://github.com/SunsetTechuila/imaged-folders/assets/152434390/a345c50d-82ad-47d2-b4ff-a9fa44f06b59)
![Screenshot (152)](https://github.com/SunsetTechuila/imaged-folders/assets/152434390/c47caa6c-a061-455e-8c17-ec7983e3a752)

**Comment by SunsetTechuila** [comment]
Update spicetify

**Comment by KeshavKalaivaniSuresh** [comment]
Oh it worked Thank you 
I made notice for me not checking properly ma bad
thx again
